
seed: 42
model: "cnn"          # cnn | rf
data_dir: "data"
use_sample: false
val_size: 0.1         # stratified split from train
class_names: [0,1,2,3,4,5,6,7,8]

# RF params
rf:
  n_estimators: 300
  max_depth: null
  n_jobs: -1
  random_state: 42

# CNN params
cnn:
  batch_size: 128
  epochs: 20
  patience: 5
  learning_rate: 0.001
  tune: false     # set true for KerasTuner (small search)
